<%
'---- ParameterDirectionEnum Values ----
Const adParamUnknown = &H0000
Const adParamInput = &H0001
Const adParamOutput = &H0002
Const adParamInputOutput = &H0003
Const adParamReturnValue = &H0004

'---- DataTypeEnum Values ----
Const adInteger = 3
Const adBigInt = 20
Const adCurrency = 6
Const adDecimal = 14
Const adBoolean = 11
Const adDBTime = 134
Const adChar = 129
Const adVarChar = 200
'--------
const adcmdstoredproc = &H0004
const adCmdText=1

Const adDouble = 5
Const adVarWChar = 202
Const adLongVarChar = 201
Const adDBDate = 133
Const adDBTimeStamp = 135

%>